## To build this documentation using mkdocs :
##    python -m pip install mkdocs pymdown-extensions plantuml_markdown
## On linux, go to this directory, then
##    chmod +x plantuml
##    export LD_LIBRARY_PATH=$PWD:$LD_LIBRARY_PATH
## On windows, go to this directory, then
##    set PATH=%PATH%;%CD%
## Then build & run the doc using mkdocs 
##    mkdocs build ; mkdocs serve
##    # Open the browsers http://localhost:8000
##
##
site_name: Nakasendo
#site_name: 'https://nakasendoproject.org/assets/nakasendo_logo_white.svg'

nav:
    - Nakasendo SDK : index.md
    - QuickStart : QuickStart.md
    - Primitives : Primitives.md
    - Developer setup : DeveloperSetup.md

markdown_extensions:
  - toc:
  - pymdownx.arithmatex
  - plantuml_markdown:

extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML' # mathjax

theme: readthedocs

extra_css:
    - css/theme_extra.css
